### ISSUE TITLE
Error running git in version 0.3.0, works in 0.2.0

### ISSUE THREAD

**Issue by gmishkin** [mongodb-labs/drone-bazelisk-ecr#10]
I had an issue with drone-bazelisk-ecr 0.3.0, it complains about ownership of /drone/src and needs setting of git config safe.directory which can only be set "globally" (i.e. it can't be in /drone/src/.gitconfig) and so doesn't persist between steps.

```
fatal: detected dubious ownership in repository at '/drone/src'
```

ref: https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory

**Comment by whwalter** [comment]
Try the fix version [amd64](public.ecr.aws/kanopy/drone-bazelisk-ecr@sha256:9f1b0d635c83371729e103c3967d0f540caa21f6252da948b4a15e8164e03167) or [arm64](public.ecr.aws/kanopy/drone-bazelisk-ecr@sha256:636cba9288cb0d247f1ae501707dede0893fd7fcb646bdfe10d6aa10e24c7ba3 ) image out and let me know if it resolves the issue. 

If it does, I can cut a new minor release. If it doesn't, I might need a minimal code replication example I can develop some tests against.

**Comment by gmishkin** [comment]
I am doing some testing and happened to update to 0.3.2 as part of it and it seems like this isn't happening anymore.
